import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';

/**
 * Reads dist/webview/webview-ui/index.html (generated by Vite), rewrites all
 * relative asset src/href attributes to proper webview URIs, and injects a
 * CSP nonce + meta tag so VS Code's Webview sandbox accepts the scripts.
 *
 * This approach is robust against Vite's content-hashed filenames — we never
 * hardcode asset names; we just let Vite's own output HTML tell us what they are.
 */
export function getWebviewHtml(
    webview: vscode.Webview,
    extensionUri: vscode.Uri,
    /** Value to set on <div id="root" data-panel="..."> for panel routing. */
    panelName: 'story' | 'settings' | 'generation-review' | 'sync-review' | 'agent-prompt',
): string {
    const distWebview = vscode.Uri.joinPath(extensionUri, 'dist', 'webview');
    const indexPath = path.join(distWebview.fsPath, 'webview-ui', 'index.html');

    let html: string;
    try {
        html = fs.readFileSync(indexPath, 'utf-8');
    } catch {
        return errorHtml('Webview bundle not found. Run <code>npm run compile:webview</code> then reload the Extension Development Host.');
    }

    const nonce = getNonce();
    const assetsBase = webview.asWebviewUri(vscode.Uri.joinPath(distWebview, 'assets'));

    // Rewrite src="../assets/xxx" and href="../assets/xxx" to full webview URIs.
    html = html.replace(/(src|href)="\.\.\/assets\/([^"]+)"/g, (_match, attr, file) => {
        const uri = webview.asWebviewUri(vscode.Uri.joinPath(distWebview, 'assets', file));
        return `${attr}="${uri}"`;
    });

    // Also rewrite any direct assets/ references (Vite sometimes emits without the ../)
    html = html.replace(/(src|href)="assets\/([^"]+)"/g, (_match, attr, file) => {
        const uri = webview.asWebviewUri(vscode.Uri.joinPath(distWebview, 'assets', file));
        return `${attr}="${uri}"`;
    });

    // Add nonce to all <script> tags so the CSP allows them.
    html = html.replace(/<script /g, `<script nonce="${nonce}" `);

    // Inject CSP meta tag right after <head>.
    const csp = [
        `default-src 'none'`,
        `style-src ${webview.cspSource} 'unsafe-inline'`,
        `script-src 'nonce-${nonce}'`,
        `img-src ${webview.cspSource} data:`,
        `font-src ${webview.cspSource}`,
    ].join('; ');

    html = html.replace(
        '<head>',
        `<head>\n    <meta http-equiv="Content-Security-Policy" content="${csp}" />`,
    );

    // Set data-panel attribute on the root div for panel routing in main.tsx.
    html = html.replace(
        '<div id="root">',
        `<div id="root" data-panel="${panelName}">`,
    );

    // Suppress the Vite modulepreload polyfill crossorigin issue in Webview context.
    // (The links are fine; this just avoids a noisy console warning.)
    html = html.replace(/crossorigin/g, '');

    void assetsBase; // referenced above via asWebviewUri calls
    return html;
}

function getNonce(): string {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    return Array.from({ length: 32 }, () => chars[Math.floor(Math.random() * chars.length)]).join('');
}

function errorHtml(message: string): string {
    return `<!DOCTYPE html><html><body style="font-family:sans-serif;padding:2rem;color:#f48771">
    <h2>Saga — Webview load error</h2><p>${message}</p>
    </body></html>`;
}
